from __future__ import annotations

from typing import Protocol

from .models import CheckpointRecord, Event, PrecedentRecord, Run


class RunRepository(Protocol):
    def create(self, run: Run) -> Run: ...
    def update(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Run | None: ...
    def list(self) -> list[Run]: ...


class EventRepository(Protocol):
    def append(self, event: Event) -> Event: ...
    def list_by_run(self, run_id: str) -> list[Event]: ...


class CheckpointRepository(Protocol):
    def save(self, checkpoint: CheckpointRecord) -> CheckpointRecord: ...
    def get_latest(self, run_id: str) -> CheckpointRecord | None: ...


class PrecedentRepository(Protocol):
    def save(self, precedent: PrecedentRecord) -> PrecedentRecord: ...
    def list_by_rule(self, rule_id: str | None = None) -> list[PrecedentRecord]: ...

